[[pages]]
path = "pages_section/introduction_page.py"
name = "Home"
icon = "ğŸ "  # Home emoji

[[pages]]
path = "pages_section/qr_code_generator.py"
name = "QR Code Generator"
icon = "ğŸ“·"  # Camera emoji

[[pages]]
path = "pages_section/bg_remover.py"
name = "Background Remover"
icon = "ğŸ–¼ï¸"  # Framed picture emoji

[[pages]]
path = "pages_section/image_to_pdf.py"
name = "Image to PDF"
icon = "ğŸ“„"  # Page emoji